//API calling
export const API_CALLING = "API_CALLING"

//Login-Admin
export const LOGIN_ADMIN = "LOGIN_ADMIN"
export const SUA_THONG_TIN_ADMIN = "SUA_THONG_TIN_ADMIN"
export const DOI_MAT_KHAU = "DOI_MAT_KHAU"

//Khu Nha
export const HIEN_THI_CAC_KHU_NHA = "HIEN_THI_CAC_KHU_NHA"
export const LAY_KHU_NHA_ID = "LAY_KHU_NHA_ID"
export const THEM_KHU_NHA = "THEM_KHU_NHA"
export const SUA_KHU_NHA = "SUA_KHU_NHA"
export const XOA_KHU_NHA = "XOA_KHU_NHA"

//Phong
export const HIEN_THI_CAC_PHONG = "HIEN_THI_CAC_KHU_PHONG"
export const LAY_PHONG_ID = "LAY_PHONG_ID"
export const THEM_PHONG = "THEM_PHONG"
export const SUA_PHONG = "SUA_PHONG"
export const XOA_PHONG = "XOA_PHONG"
export const THEM_SINH_VIEN = "THEM_SINH_VIEN"

//Sinh-Vien
export const LOGIN_SINH_VIEN = "LOGIN_SINH_VIEN"
export const SIGNUP_SINH_VIEN = "SIGN_UP_SINH_VIEN"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const SIGNUP_ERROR = "SIGNUP_ERROR"
export const DANG_KI_PHONG = "DANG_KI_PHONG"
export const KIEM_TRA_SINH_VIEN_THUOC_KTX = "KIEM_TRA_SINH_VIEN_THUOC_KTX"
export const ROI_KTX = "ROI_KTX"

//Quan-Ly-Dang_ki
export const HIEN_THI_CAC_DON_DANG_KI = "HIEN_THI_CAC_DON_DANG_KI"
export const THAY_DOI_TRANG_THAI_DON = "THAY_DOI_TRANG_THAI_DON"
export const HIEN_THI_CAC_HOP_DONG = "HIEN_THI_CAC_HOP_DONG"
export const TAO_HOP_DONG = "TAO_HOP_DONG"
export const THAY_DOI_TRANG_THAI_HOP_DONG = "THAY_DOI_TRANG_THAI_HOP_DONG"

//Quan-Ly-Roi-KTX
export const HIEN_THI_CAC_DON_ROI_KTX = "HIEN_THI_CAC_DON_ROI_KTX"
export const THAY_DOI_TRANG_THAI_DON_ROI_KTX = "THAY_DOI_TRANG_THAI_DON_ROI_KTX"

//Quan-ly-dien-nuoc
export const HIEN_THI_CAC_HOA_DON_DIEN_NUOC = "HIEN_THI_CAC_HOA_DON_DIEN_NUOC"
export const HIEN_THI_CAC_HOA_DON_DIEN_NUOC_CUA_PHONG = "HIEN_THI_CAC_HOA_DON_DIEN_NUOC_CUA_PHONG"
export const TAO_DIEN_NUOC = "TAO_DIEN_NUOC"
export const THAY_DOI_TRANG_THAI_DIEN_NUOC = "THAY_DOI_TRANG_THAI_DIEN_NUOC"

//Thiet-Bi
export const HIEN_THI_CAC_THIET_BI = "HIEN_THI_CAC_THIET_BI"
export const THEM_THIET_BI = "THEM_THIET_BI"
export const NHAP_THIET_BI = "NHAP_THIET_BI"
export const THEM_THIET_BI_VAO_PHONG = "THEM_THIET_BI_VAO_PHONG"

//Quan-Ly-Hoa-Don
export const HIEN_THI_CAC_HOA_DON = "HIEN_THI_CAC_HOA_DON"
export const THEM_HOA_DON_HOP_DONG = "THEM_HOA_DON_HOP_DONG"
export const THEM_HOA_DON_DIEN_NUOC = "THEM_HOA_DON_DIEN_NUOC"
export const THEM_HOA_DON = "THEM_HOA_DON"